services:
  postgres:
    image: dockerhub.timeweb.cloud/library/postgres:16-alpine
    container_name: tmobile_postgres
    environment:
      POSTGRES_DB: tmobile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pwd
    ports:
      - "5432:5432"
    restart: always